---
title: "Experience"
---
<link rel="stylesheet" href="styles.css" type="text/css">

In addition to the academic intuitions where I completed my educational degrees, I have had the privilege of working for a diversity of institutions on a wide array of projects. 

A large part of my career has been spent working for non-profit institutions. I started my experience in tagging animals while working at the Center for Shark research at Mote Marine Laboratory in Sarasota Florida. After finishing my Masters, I was hired as a staff scientist at in the Department of Conservation and Research at Monterey Bay Aquarium. Most recently I was research technician at the Anderson Cabot Center for Ocean Life at the New England Aquarium, whom I continue to collaborate with.

I have experience in the private sector working for consulting firms. I started my career at Saltwater Inc, working as an onboard observer in the Alaskan groundfish fishery. Later on, I established connections with Ecorp Consulting, where I was hired for my expertise in acoustic telemetry to investigate the impacts of pile driving on the natural behavior and movements of sand bass and bay bass.

Finally, I have worked with a diversity of governmental agencies. I was a research Technician at the Massachusetts Division of Marine Fisheries, studying the residency and movements of Sand Tiger Sharks in Boston Harbor. As a fisheries Observer I worked closely with officials at the National Marine Fisheries Service, and during my Undergrad I worked for the National Park Service monitoring stream quality. Furthermore I have collaborated with researchers at USGS, NOAA, NMFS, NPS on a diversity of different projects.
