---
title: "Presentations"
---

<link rel="stylesheet" href="styles.css" type="text/css">

## Talks

**White CF**, Moxley JH, Gleiss AC, Chapple TK, Kanive PE, Anderson SD, Carlisle AB, Block BA, Jorgensen SJ. 2017. Fine scale variability in stomach temperatures of white sharks (Carcharodon carcharias) links to digestion and homeothermy. In: 6th International Biologging Conference. Konstanz, Germany.

**White CF**, Lyons K, Weng K, Winkler C, Jorgensen SJ, O'Sullivan J, Lowe CG. 2016. Movement of Juvenile White Sharks in Southern California: Predicting Future Nursery Habitat. Annual Meeting of the American Elasmobranch Society. New Orleans, LA.

**White CF**, Lyons K, Weng K, Winkler C, Jorgensen SJ, O'Sullivan J, Lowe CG. 2016. Predicting the Distribution of Juvenile White Sharks Based on Dynamic Environmental Data. 2nd North East Pacific Shark Symposium. Catalina Island, CA.

**White CF**, Lin Y, Hsiung J, Clark CM, Lowe CG. 2015. Evaluating Autonomous Underwater Vehicles As Tools for Surveying and Tracking Tagged Fish. 145th Annual Meeting of the American Fisheries Society. Portland, OR.

**White CF**, Lin Y, Hsiung J, Clark CM, Lowe CG. 2015. Habitat Selection of the Leopard Shark, Triakis semifasciata, Using Fine Spatio-Temporal Movement and Temperature Data. American Elasmobranch Society. Reno, NV.

**White CF**, Hart KM, Cherkiss MS, Rockford MR, Mazzotti FJ, Whitney NM. 2014. Activity Patterns and Thermoregulatory Behavior of the Invasive Burmese Python, Python molurus bivittatus, in the Florida Everglades , USA.  5th International Biologging Symposium. Strasbourg, France.

**White CF**, Lin Y, Piersall R, Clark CM, Lowe CG. 2014. Using Tracking Robots and Accelerometers to Determine Fine Scale Behaviors and Habitat Selection of the Leopard Shark, Triakis semifasciata. First North East pacific Shark Symposium. Seattle, WA.

**White CF**, Anderson PA, Gleiss AC, Skomal GB, Hueter RH, Whitney NM. 2013. Assessing Post-Release Recovery Periods in Blacktip Sharks. Annual Meeting of Western Society of Naturalists. Oxnard, CA.

**White CF**, Allen JD. 2012. Embryo Protection in Nucella lapillus: Encapsulation or Aggregation? Benthic Ecology Meeting. Norfolk, VA.

**White CF**, Allen JD. 2011. The Effect of Egg Capsule Clustering on Embryonic Survival in the Dogwhelk Nucella lapillus. Society of Integrative and Comparative Biology. Salt Lake City, UT. pp E266-E266.




